# Jacob Sheehan
## Week 9 10/15/2024
### Python Numpy

In [1]:
#slicing np arrays
## [start:end:step] start 0, end array size, tep is considered1, end index is excluded
# 1-D array



In [3]:
import numpy as np
arr_1d = np.array([1,2,3,4,5])

In [4]:
arr_1d

array([1, 2, 3, 4, 5])

In [6]:
arr_1d[3:-1]

array([4])

In [12]:
#slicing 2-D Arrays
arr_2d = np.array([[1,2,3,4,5,16], [8,8,9,10,12]])

In [13]:
arr_2d.shape

(2,)

In [14]:
arr_2d.ndim

1

In [15]:
arr_2d[:2]

array([list([1, 2, 3, 4, 5, 16]), list([8, 8, 9, 10, 12])], dtype=object)

In [17]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d.shape) 

(2, 3)


In [19]:
array_2d[:,-1]

array([3, 6])

In [20]:
# 3-D arrays
# star:stop:step three times
array_3d = np.array([[[1, 2], [3, 4]], 
                     
                      [[5, 6], [7, 8]], 
                     
                      [[9, 10], [11, 12]]])

In [21]:
array_3d

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [22]:
array_3d.shape

(3, 2, 2)

In [23]:
array_3d[0:1]

array([[[1, 2],
        [3, 4]]])

In [24]:
array_3d[:,0]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [26]:
array_3d[:,:] #This gives you the entire list

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [29]:
array_3d[:,1,-1:]

array([[ 4],
       [ 8],
       [12]])

In [31]:
array_3d[:,1,:2]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [38]:
array_3d[2::]

array([[[ 9, 10],
        [11, 12]]])

In [46]:
array_3d[2:,0,:2]

array([[ 9, 10]])

In [47]:
# Different data elemetss dims
arr_d = np.array([ [[1,2],[3,4]], [[5,6,7], [8,9,10]] ])

In [49]:
arr_d

array([[list([1, 2]), list([3, 4])],
       [list([5, 6, 7]), list([8, 9, 10])]], dtype=object)

In [50]:
arr_d.ndim

2

In [51]:
arr_d.shape

(2, 2)

In [54]:
arr_d = np.array([ [[1,2],[3,4]], [[5,6,], [8,9,]] ]) #Have all elemts equal each for 3d array
arr_d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [8, 9]]])