# Jacob Sheehan
## Week 10 10/24/24
### Python Numpy - Creating, Processing, Transporting NP Arrays

In [1]:
import numpy as np
# zeros
arr_1d = np.zeros(10)
arr_1d

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [2]:
arr_2d = np.zeros((5,10))
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [3]:
arr_1d + 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [4]:
arr_2d + 5

array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [5]:
arr = np.ones((5,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
arr = np.ones((5,5,2))
arr

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [7]:
arr.shape

(5, 5, 2)

In [8]:
arr * .5

array([[[0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5]],

       [[0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5]],

       [[0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5]],

       [[0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5]],

       [[0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5]]])

In [9]:
arr

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [10]:
arr = np.empty((5,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
arr = np.empty((5,2))
arr

array([[5., 5.],
       [5., 5.],
       [5., 5.],
       [5., 5.],
       [5., 5.]])

In [12]:
arr = np.empty((2,2,2))
arr

array([[[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 6.16593926e-321],
        [8.34454049e-308, 2.29175545e-312]]])

In [14]:
arr = np.empty((2,2,2), dtype=int)
arr

array([[[  825303084,   170679645],
        [ -442949216,         439]],

       [[          0,           0],
        [-2147483648,  1970426912]]])

In [15]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr = np.arange(10,101,10)
arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [17]:
# Reshape an array
# Reshape 1-D to 2-D
arr_1d = np.arange(1,13,1)
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [18]:
arr_2d = arr_1d.reshape(2,6)
arr_2d

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [19]:
arr_2d = arr_1d.reshape(3,4)
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [21]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
arr_1d[:4] = [0,0,0,0]
arr_1d

array([ 0,  0,  0,  0,  5,  6,  7,  8,  9, 10, 11, 12])

In [23]:
arr_2d

array([[ 0,  0,  0,  0],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
arr_2d = np.arange(1,13,1).reshape(3,4)
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
#reshape from 2-d to 3-d
arr_3d = np.arange(1,13,1).reshape(2,3,2)
arr_3d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [27]:
# Pass -1 as the value, and Nump=Py will calculate this number for you.
arr_3d = np.arange(1,13,1).reshape(2,-1,2)
arr_3d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [29]:
arr_3d = np.arange(1,13,1).reshape(2,2,-1)
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [30]:
# Reshape 3-D to 1-D
arr_3d.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [32]:
# Reshape 3d to 2d
arr_2d = arr_3d.reshape((-1,3))

In [33]:
arr_2d.shape

(4, 3)

In [34]:
# Iterating 1-D
for n in arr_1d:
    print(n)

0
0
0
0
5
6
7
8
9
10
11
12


In [35]:
# Iterating 2-D
for n in arr_2d:
    print(n)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [38]:
for n in arr_2d:
    for num in n:
        print(num, end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 

In [40]:
# Iterating 3_D arrays
for n in arr_3d:
    print(n)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [43]:
for n in arr_3d:
    for num in n:
        for yup in num:
            print(yup, end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 

In [42]:
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [44]:
# nditer iterates on each scalar elemt in the np array
for n in np.nditer(arr_3d):
    print(n, end=' ')

1 2 3 4 5 6 7 8 9 10 11 12 

In [45]:
for n in np.nditer(arr_2d):
    print(n, end=' ')

1 2 3 4 5 6 7 8 9 10 11 12 

In [47]:
# Multidimensinal index iterator.
# np.ndenumerate()
for i,n in np.ndenumerate(arr_1d):
    print(i,n)

(0,) 0
(1,) 0
(2,) 0
(3,) 0
(4,) 5
(5,) 6
(6,) 7
(7,) 8
(8,) 9
(9,) 10
(10,) 11
(11,) 12


In [51]:
for i,n in np.ndenumerate(arr_3d):
    print(i,n)
# The first 0 is the first 2-d ARRARY. THen it goes row column row column

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12


In [52]:
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [53]:
arr_3d[:,:,-2]

array([[ 2,  5],
       [ 8, 11]])

In [54]:
arr_3d[...,-2:]

array([[[ 2,  3],
        [ 5,  6]],

       [[ 8,  9],
        [11, 12]]])

In [55]:
for n in np.nditer(arr_3d[...,-2:]):
    print(n, end=' ')

2 3 5 6 8 9 11 12 