# Jacob Sheehan
## Week10 10/22/2024
### Python Numpy - Processing Arrays

In [2]:
import numpy as np

In [6]:
lst1 = list(range(1,6))
lst2 = list(range(6,11))

In [7]:
lst1

[1, 2, 3, 4, 5]

In [8]:
lst2

[6, 7, 8, 9, 10]

In [10]:
lst = [lst1,lst2]
lst

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [12]:
arr_2d = np.array(lst)
arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [13]:
arr_2d.shape

(2, 5)

In [14]:
arr_2d.dtype

dtype('int32')

In [15]:
arr_1d = np.array(['Orange','Apple','Cherry','Grape'])
arr_1d

array(['Orange', 'Apple', 'Cherry', 'Grape'], dtype='<U6')

In [18]:
arr_1d.dtype

dtype('<U6')

In [19]:
arr = np.array(['Orange','Apple','Cherry','Grape', 1.5, 2.8, 4.9, (1,2,3,4), [4,5,6], True, False])
arr.dtype

dtype('O')

In [20]:
arr

array(['Orange', 'Apple', 'Cherry', 'Grape', 1.5, 2.8, 4.9, (1, 2, 3, 4),
       list([4, 5, 6]), True, False], dtype=object)

In [21]:
# Convert Data Types
arr = np.array([10,11,12,13,14,15], dtype = 'S')
arr

array([b'10', b'11', b'12', b'13', b'14', b'15'], dtype='|S2')

In [22]:
print(arr)

[b'10' b'11' b'12' b'13' b'14' b'15']


In [23]:
arr[0]

b'10'

In [26]:
arr = np.array(list(range(1,6)), dtype='i4')
arr

array([1, 2, 3, 4, 5])

In [27]:
arr.dtype

dtype('int32')

In [28]:
arr = np.array(list(range(5,11)), dtype='i8')
arr

array([ 5,  6,  7,  8,  9, 10], dtype=int64)

In [29]:
arr.dtype

dtype('int64')

In [30]:
# Converting Data Type on Exisiting Arrays
arr = np.array([78.5, 88.9, 90.3, 89.9, 87.6])
arr

array([78.5, 88.9, 90.3, 89.9, 87.6])

In [31]:
arr.dtype

dtype('float64')

In [32]:
# astype()
arr_int = arr.astype('i')
arr_int

array([78, 88, 90, 89, 87], dtype=int32)

In [33]:
arr

array([78.5, 88.9, 90.3, 89.9, 87.6])

In [34]:
arr_int

array([78, 88, 90, 89, 87], dtype=int32)

In [35]:
arr = np.array([1,0,2,3,1,0,0,2])
arr

array([1, 0, 2, 3, 1, 0, 0, 2])

In [36]:
arr_b = arr.astype(bool)
arr_b

array([ True, False,  True,  True,  True, False, False,  True])

In [3]:
# NumPy Array Copy vs View
'''
The difference between copy vs View
Copy is a new array, and the view is just a view of the original array

'''

arr1 = np.array(list(range(10,16)))

In [4]:
arr2 = arr1
arr2
arr2_copy = arr1.copy # Copy is a new numpy arrary

In [5]:
arr2_copy

<function ndarray.copy>

In [6]:
arr1

array([10, 11, 12, 13, 14, 15])

In [7]:
arr2_view = arr1.view # a view of the original array
arr2_view

<function ndarray.view>

In [8]:
arr2_view

<function ndarray.view>

In [9]:
arr2

array([10, 11, 12, 13, 14, 15])

In [10]:
print(arr2_copy.base)

AttributeError: 'builtin_function_or_method' object has no attribute 'base'

AttributeError: 'builtin_function_or_method' object has no attribute 'base'

In [12]:
# shape gives the number of elemets in each dimension
arr = np.array([list(range(1,6)), list(range(6,11))])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [13]:
arr.shape

(2, 5)

In [14]:
arr.shape[0] #Amount of rows

2

In [15]:
arr.shape[1] #Amonut of elements

5

In [16]:
# Stacking: Several arrays can be stacked together along different axes. 
# np.vstack: To stack arrays along vertical axis. 
# np.hstackL To stack arrays along horizontal axis.
a = np.array([[1, 2],[3, 4]])

b = np.array([[5, 6],[7, 8]])

In [17]:
a

array([[1, 2],
       [3, 4]])

In [18]:
b

array([[5, 6],
       [7, 8]])

In [19]:
a.ndim

2

In [20]:
len(a)

2

In [21]:
a.shape

(2, 2)

In [22]:
# vertical stacking
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [23]:
# Horizontal Stacking
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [24]:
np.hstack((b,a))

array([[5, 6, 1, 2],
       [7, 8, 3, 4]])

In [25]:
# create numpy array from files
f = open("data.txt", "w")
f.write("1, 2, 3\n")
f.write("4, 5, 6")
f.close()

In [27]:
#read
f = open("data.txt", "r")
print(f.read())

1, 2, 3
4, 5, 6


In [28]:
# Using np.genfromtxt
arr = np.genfromtxt("data.txt", dtype=None, delimiter=",")

In [29]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
arr.ndim

2

In [31]:
arr.shape

(2, 3)

In [33]:
# using np.loadtxt
arr = np.loadtxt("data.txt", dtype="i", delimiter=",")
arr

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [34]:
arr = np.loadtxt("data.txt", dtype="<U6")
arr

array([['1,', '2,', '3'],
       ['4,', '5,', '6']], dtype='<U6')

In [35]:
arr = np.loadtxt("data.txt", dtype="S")
arr

array([[b'1,', b'2,', b'3'],
       [b'4,', b'5,', b'6']], dtype='|S2')