# Jacob Sheehan
## Week 11 10/29/24
### Python NumPy Universal Functions

In [1]:
# Universal functions are a powerful tools for performing mathematical operations on NumPy arrays.
import numpy as np
arr_1d = np.arange(21)
arr_1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [2]:
# sqrt
np.sqrt(arr_1d)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [3]:
#exp()
np.exp(arr_1d)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08])

In [4]:
# The numpy.random.randn() functions creates
arr_1d = np.random.randn(10)
arr_1d

array([ 0.10155312,  0.11129153,  1.96506479,  0.26245392,  0.82597497,
       -0.92228339,  1.39559152, -1.42106264, -0.68589518,  0.86259752])

In [5]:
arr_1d = np.random.randn(10)
arr_1d

array([ 0.35031626,  1.57551394, -0.47036691,  0.26520902, -1.67241863,
        0.43355795, -1.1690851 ,  1.23906609, -1.11259166,  1.94473849])

In [6]:
arr_2d = np.random.randn(4,5)
arr_2d

array([[ 0.87528565, -0.21707544, -0.89295074, -0.16063654,  1.17759856],
       [-0.40612452,  1.26824593, -1.75736645,  1.58643654, -0.21239582],
       [-0.29537996,  0.52478795, -0.72983843, -1.22421574,  0.19956598],
       [ 0.51579165, -1.25329045,  0.76457086,  0.2448945 , -0.53469086]])

In [7]:
arr_3d = np.random.randn(4,5,2)
arr_3d

array([[[ 0.52213713,  0.09760635],
        [-1.01856423,  0.24916672],
        [-2.10786395, -1.18885008],
        [ 0.70306266,  0.64320018],
        [-0.73690513,  0.44954208]],

       [[ 0.19599694,  0.63592893],
        [ 0.58944486,  0.10642491],
        [ 0.53850965,  0.72047842],
        [ 0.75171246,  0.68585956],
        [-0.24694198,  0.04818885]],

       [[-0.99177396,  0.03194809],
        [-1.99703927,  1.66485745],
        [ 0.76761307,  0.09693245],
        [-1.37232394,  0.07598341],
        [ 0.86667473,  1.24938565]],

       [[ 0.89366239, -0.05622183],
        [-0.51737555, -0.51141854],
        [-0.71208707,  0.0574042 ],
        [-0.73658634,  0.40166402],
        [-1.11015688,  0.38103817]]])

In [8]:
arr_1d

array([ 0.35031626,  1.57551394, -0.47036691,  0.26520902, -1.67241863,
        0.43355795, -1.1690851 ,  1.23906609, -1.11259166,  1.94473849])

In [9]:
arr_11d = np.random.randn(10)
arr_11d

array([-0.9550946 ,  1.73577463, -0.23842543, -0.08465148,  1.70386716,
       -0.66643878, -0.79278747, -2.09862118,  0.06833896,  0.90325774])

In [10]:
np.add(arr_1d,arr_11d)

array([-0.60477835,  3.31128857, -0.70879234,  0.18055754,  0.03144854,
       -0.23288083, -1.96187257, -0.85955509, -1.0442527 ,  2.84799622])

In [11]:
# maximum
np.maximum(arr_1d,arr_11d)

array([ 0.35031626,  1.73577463, -0.23842543,  0.26520902,  1.70386716,
        0.43355795, -0.79278747,  1.23906609,  0.06833896,  1.94473849])

In [12]:
np.minimum(arr_1d,arr_11d)

array([-0.9550946 ,  1.57551394, -0.47036691, -0.08465148, -1.67241863,
       -0.66643878, -1.1690851 , -2.09862118, -1.11259166,  0.90325774])

In [13]:
arr1 = np.arange(9).reshape((3,3))
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
arr2 = np.ones(9).reshape((3,3))
arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.add(arr1,arr2)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [16]:
# Array filtering
arr1 < 4

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False]])

In [17]:
arr_2d <= 2

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [18]:
arr_2d > 0

array([[ True, False, False, False,  True],
       [False,  True, False,  True, False],
       [False,  True, False, False,  True],
       [ True, False,  True,  True, False]])

In [19]:
arr_3d > 0

array([[[ True,  True],
        [False,  True],
        [False, False],
        [ True,  True],
        [False,  True]],

       [[ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True],
        [False,  True]],

       [[False,  True],
        [False,  True],
        [ True,  True],
        [False,  True],
        [ True,  True]],

       [[ True, False],
        [False, False],
        [False,  True],
        [False,  True],
        [False,  True]]])

In [20]:
# using where()
# replace values of an array, using where
from numpy.random import randn
arr = randn(3,3)
arr

array([[-1.02746462,  1.5991327 ,  1.19304465],
       [-0.98779412, -0.09015111,  2.99895771],
       [-1.0143887 ,  0.66982503, -0.57104093]])

In [21]:
np.where(arr<0,0,arr)

array([[0.        , 1.5991327 , 1.19304465],
       [0.        , 0.        , 2.99895771],
       [0.        , 0.66982503, 0.        ]])

In [22]:
np.where(arr<0,0,1)

array([[0, 1, 1],
       [0, 0, 1],
       [0, 1, 0]])

In [23]:
np.where([True,True,False], 1,0)

array([1, 1, 0])

In [24]:
arr

array([[-1.02746462,  1.5991327 ,  1.19304465],
       [-0.98779412, -0.09015111,  2.99895771],
       [-1.0143887 ,  0.66982503, -0.57104093]])

In [25]:
np.where(arr > -1, 1,0) # if arr is less than -1 replace with 1 if not than 0

array([[0, 1, 1],
       [1, 1, 1],
       [0, 1, 1]])

In [26]:
np.where((arr < 0.5) & (arr > 0), 4,2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [27]:
# Array for random sampling of True and False values
sample = [True,False]
arr_bool = np.random.choice(sample,size=10)
arr_bool

array([False, False,  True,  True,  True, False, False, False,  True,
        True])

In [28]:
arr1 = np.arange(1,11)
arr2 = np.arange(1,11)*10

In [29]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
arr2

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [31]:
arr = np.where(arr_bool,arr1,arr2)
arr

array([10, 20,  3,  4,  5, 60, 70, 80,  9, 10])

In [32]:
# using list comprehension
arr = [r1 if c else r2 for r1,r2,c in zip(arr1,arr2,arr_bool)]
arr


[10, 20, 3, 4, 5, 60, 70, 80, 9, 10]

In [33]:
list(zip(arr1,arr2,arr_bool))

[(1, 10, False),
 (2, 20, False),
 (3, 30, True),
 (4, 40, True),
 (5, 50, True),
 (6, 60, False),
 (7, 70, False),
 (8, 80, False),
 (9, 90, True),
 (10, 100, True)]

In [34]:
# using where with 2-D array
arr1 = np.arange(1,5).reshape(2,2)
arr2 = np.arange(5,9).reshape(2,2)


In [35]:
arr1

array([[1, 2],
       [3, 4]])

In [36]:
arr2

array([[5, 6],
       [7, 8]])

In [37]:
arr_bool = np.random.choice(sample,size=4).reshape(2,2)
arr_bool

array([[ True, False],
       [ True, False]])

In [38]:
arr = np.where(arr_bool,arr1,arr2)
arr

array([[1, 6],
       [3, 8]])

In [39]:
# all()
arr_bool = np.random.choice(sample,size = 5)
arr_bool

array([False,  True, False, False,  True])

In [40]:
arr_bool.all()

False

In [41]:
# any()
# all()
arr_bool = np.random.choice(sample,size = 5)
arr_bool

array([ True,  True, False, False, False])

In [42]:
arr_bool.any()

True

In [43]:
# unique()
fruits = np.array(['Apple','Cherry','Apple', 'Orange', 'Cherry','Banana'])
fruits

array(['Apple', 'Cherry', 'Apple', 'Orange', 'Cherry', 'Banana'],
      dtype='<U6')

In [44]:
np.unique(fruits)

array(['Apple', 'Banana', 'Cherry', 'Orange'], dtype='<U6')

In [45]:
set(fruits)

{'Apple', 'Banana', 'Cherry', 'Orange'}

In [46]:
fruits

array(['Apple', 'Cherry', 'Apple', 'Orange', 'Cherry', 'Banana'],
      dtype='<U6')

In [47]:
'Apple' in set(fruits)

True

In [48]:
np.in1d(['Apple','Cherry','Grape'], fruits)

array([ True,  True, False])

In [49]:
# Descriptive Statistical Measures
arr = np.arange(1,10).reshape(3,3)

In [50]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
arr.sum()

45

In [52]:
#axis0
arr.sum(0)

array([12, 15, 18])

In [53]:
arr.sum(1)

array([ 6, 15, 24])

In [54]:
np.sum(arr)

45

In [55]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [56]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [57]:
print(arr.mean(), ' ', arr.mean(0), ' ', arr.mean(1))

5.0   [4. 5. 6.]   [2. 5. 8.]


In [58]:
print(np.mean(arr), ' ', np.mean(arr,axis=0), ' ', np.mean(arr,axis=1))

5.0   [4. 5. 6.]   [2. 5. 8.]


In [59]:
print(arr.std(), ' ', arr.std(0), ' ', arr.std(1))

2.581988897471611   [2.44948974 2.44948974 2.44948974]   [0.81649658 0.81649658 0.81649658]


In [60]:
# dot product of two arrays
arr1 = np.arange(5,20).reshape((3,5))
arr1

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [61]:
arr2 = np.random.random((5,4)) * 10
arr2 = arr2.astype(int)
arr2

array([[3, 7, 8, 6],
       [5, 5, 5, 6],
       [0, 8, 3, 8],
       [9, 5, 3, 3],
       [5, 6, 8, 1]])

In [62]:
np.dot(arr1,arr2)

array([[162, 215, 187, 155],
       [272, 370, 322, 275],
       [382, 525, 457, 395]])

In [63]:
# Random - Different random - short import
from numpy.random import randn, random

In [64]:
random((2,4))

array([[0.44758883, 0.4897723 , 0.96638574, 0.91561835],
       [0.95701838, 0.11351533, 0.06461615, 0.74098358]])

In [65]:
random((3,3,3))

array([[[0.91964861, 0.93488112, 0.08497319],
        [0.22424613, 0.87652832, 0.26727643],
        [0.99436198, 0.91647634, 0.83580974]],

       [[0.05651059, 0.73165227, 0.08490278],
        [0.64711838, 0.93199254, 0.32960271],
        [0.23497724, 0.0231927 , 0.65953732]],

       [[0.09381052, 0.97857175, 0.50245335],
        [0.3300575 , 0.37461759, 0.37389538],
        [0.19861016, 0.53011243, 0.55660312]]])

In [66]:
# Joining NumPy Arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1,arr2))
arr

array([1, 2, 3, 4, 5, 6])

In [67]:
arr1 = np.arange(1,5).reshape(2,2)
arr2 = np.arange(5,9).reshape(2,2)

In [68]:
arr1

array([[1, 2],
       [3, 4]])

In [69]:
arr2

array([[5, 6],
       [7, 8]])

In [70]:
np.concatenate((arr1,arr2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [71]:
np.concatenate((arr1,arr2), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [72]:
np.concatenate((arr1,arr2), axis = 1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [73]:
# Splitting NumPy Arrays
arr = random(10) * 10
arr


array([8.14717291, 2.33306832, 3.99108249, 2.47736162, 0.23376562,
       5.84043019, 7.15087475, 2.31874873, 0.20447499, 7.46400803])

In [74]:
arr_split = np.array_split(arr,5)
arr_split

[array([8.14717291, 2.33306832]),
 array([3.99108249, 2.47736162]),
 array([0.23376562, 5.84043019]),
 array([7.15087475, 2.31874873]),
 array([0.20447499, 7.46400803])]

In [75]:
arr_split[0].astype(int)

array([8, 2])

In [76]:
# Using numpy to fond out highre scores in two exams
test1 = np.rint(random(50) * 101)
test2 = np.rint(random(50) * 101)

In [77]:
test1

array([ 73.,  91.,  70.,  17.,  27.,  50.,   2.,  45.,  48.,  76.,  68.,
        16.,  37.,   5.,  48.,  87.,  38.,  46.,  82.,   1.,  16.,  52.,
        25.,  45.,  91., 100.,  77.,   9.,  88.,  61.,  49.,  64.,  73.,
        66.,  30.,  66.,  41.,  94.,  98.,  91.,  23.,  84.,  31.,  46.,
        72.,  48.,  98.,  19.,  90.,  79.])

In [78]:
test2

array([ 47.,  47.,  80.,  46.,  71.,  27.,  77.,  49.,  33.,  54.,  69.,
        60.,   0.,  80.,  67.,  76.,  13.,  62.,  65.,  66.,  45.,   5.,
        82.,  20.,   3.,  53.,  57.,  43.,  48.,   7.,  11.,   8.,   8.,
        74.,  40.,  18.,  40.,  69.,  68., 100.,  24.,  29.,  23.,  93.,
        95.,  53.,  79.,  67.,  82.,  62.])

In [79]:
test1.max()

100.0

In [80]:
test1.min()

1.0

In [81]:
test2.max()

100.0

In [82]:
test2.min()

0.0

In [83]:
test = np.maximum(test1,test2)
test

array([ 73.,  91.,  80.,  46.,  71.,  50.,  77.,  49.,  48.,  76.,  69.,
        60.,  37.,  80.,  67.,  87.,  38.,  62.,  82.,  66.,  45.,  52.,
        82.,  45.,  91., 100.,  77.,  43.,  88.,  61.,  49.,  64.,  73.,
        74.,  40.,  66.,  41.,  94.,  98., 100.,  24.,  84.,  31.,  93.,
        95.,  53.,  98.,  67.,  90.,  79.])

In [84]:
test.max()

100.0

In [85]:
test.min()

24.0

In [86]:
np.where(test1 > test2, test1,test2)

array([ 73.,  91.,  80.,  46.,  71.,  50.,  77.,  49.,  48.,  76.,  69.,
        60.,  37.,  80.,  67.,  87.,  38.,  62.,  82.,  66.,  45.,  52.,
        82.,  45.,  91., 100.,  77.,  43.,  88.,  61.,  49.,  64.,  73.,
        74.,  40.,  66.,  41.,  94.,  98., 100.,  24.,  84.,  31.,  93.,
        95.,  53.,  98.,  67.,  90.,  79.])

In [87]:
test_bool = test1 > test2
test_bool

array([ True,  True, False, False, False,  True, False, False,  True,
        True, False, False,  True, False, False,  True,  True, False,
        True, False, False,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False, False,  True,
        True,  True,  True, False, False,  True,  True, False, False,
       False,  True, False,  True,  True])

In [88]:
np.where(test_bool, test1,test2)

array([ 73.,  91.,  80.,  46.,  71.,  50.,  77.,  49.,  48.,  76.,  69.,
        60.,  37.,  80.,  67.,  87.,  38.,  62.,  82.,  66.,  45.,  52.,
        82.,  45.,  91., 100.,  77.,  43.,  88.,  61.,  49.,  64.,  73.,
        74.,  40.,  66.,  41.,  94.,  98., 100.,  24.,  84.,  31.,  93.,
        95.,  53.,  98.,  67.,  90.,  79.])

In [89]:
test[test >= 75 ]

array([ 91.,  80.,  77.,  76.,  80.,  87.,  82.,  82.,  91., 100.,  77.,
        88.,  94.,  98., 100.,  84.,  93.,  95.,  98.,  90.,  79.])